# Generated by Django 2.0.4 on 2018-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='plate',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
