# Generated by Django 2.0.4 on 2018-04-15 21:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0004_auto_20180415_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='original_listing',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
