# Generated by Django 2.0.4 on 2018-04-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0005_listing_original_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
