# Generated by Django 2.0.6 on 2018-06-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0006_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
