# Generated by Django 2.0.6 on 2018-06-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0009_auto_20180606_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='not_a_plate',
            field=models.BooleanField(default=False),
        ),
    ]
