# Generated by Django 2.0.6 on 2018-08-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0011_listing_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='lightIntensity',
            field=models.FloatField(default=1.9),
        ),
    ]
