# Generated by Django 2.0.6 on 2018-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0012_plate_lightintensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='lightIntensity',
            field=models.FloatField(default=0.8),
        ),
    ]
